# Generated by Django 4.2.6 on 2023-10-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appJukeBox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilo',
            name='bandas',
        ),
    ]
