# Generated by Django 4.2.6 on 2023-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJukeBox', '0003_alter_banda_estilos'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
